"""catalog

Revision ID: af4d8ca28960
Revises: a00aff71bcf4
Create Date: 2026-05-15 13:33:21.146890
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'af4d8ca28960'
down_revision = 'a00aff71bcf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('socials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrichment_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_index(op.f('ix_artists_slug'), 'artists', ['slug'], unique=True)
    op.create_table('media_roots',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('host_path', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_for_ingest', sa.Boolean(), nullable=False),
    sa.Column('max_bytes', sa.BigInteger(), nullable=True),
    sa.Column('naming_template', sa.String(length=255), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_roots')),
    sa.UniqueConstraint('name', name=op.f('uq_media_roots_name'))
    )
    op.create_table('series',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    op.create_index(op.f('ix_series_slug'), 'series', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('venues',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('city_or_area', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=True)
    op.create_table('parties',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_parties_series_id_series'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_parties_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties'))
    )
    op.create_index(op.f('ix_parties_series_id'), 'parties', ['series_id'], unique=False)
    op.create_index(op.f('ix_parties_slug'), 'parties', ['slug'], unique=True)
    op.create_index(op.f('ix_parties_venue_id'), 'parties', ['venue_id'], unique=False)
    op.create_table('live_sets',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('set_type', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('media_root_id', sa.UUID(), nullable=False),
    sa.Column('audio_path', sa.String(length=1024), nullable=False),
    sa.Column('streaming_path', sa.String(length=1024), nullable=True),
    sa.Column('waveform_path', sa.String(length=1024), nullable=True),
    sa.Column('thumb_path', sa.String(length=1024), nullable=True),
    sa.Column('normalized_lufs', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['live_sets.id'], name=op.f('fk_live_sets_duplicate_of_live_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_root_id'], ['media_roots.id'], name=op.f('fk_live_sets_media_root_id_media_roots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_live_sets_party_id_parties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_live_sets_uploaded_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_live_sets_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_sets'))
    )
    op.create_index(op.f('ix_live_sets_date'), 'live_sets', ['date'], unique=False)
    op.create_index(op.f('ix_live_sets_party_id'), 'live_sets', ['party_id'], unique=False)
    op.create_index(op.f('ix_live_sets_slug'), 'live_sets', ['slug'], unique=True)
    op.create_index(op.f('ix_live_sets_uploaded_by'), 'live_sets', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_live_sets_venue_id'), 'live_sets', ['venue_id'], unique=False)
    op.create_table('live_set_artists',
    sa.Column('live_set_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_live_set_artists_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['live_set_id'], ['live_sets.id'], name=op.f('fk_live_set_artists_live_set_id_live_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('live_set_id', 'artist_id', name=op.f('pk_live_set_artists'))
    )
    op.create_table('live_set_tags',
    sa.Column('live_set_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['live_set_id'], ['live_sets.id'], name=op.f('fk_live_set_tags_live_set_id_live_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_live_set_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('live_set_id', 'tag_id', name=op.f('pk_live_set_tags'))
    )
    op.create_table('set_fingerprints',
    sa.Column('live_set_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=128), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_set_id'], ['live_sets.id'], name=op.f('fk_set_fingerprints_live_set_id_live_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_fingerprints'))
    )
    op.create_index(op.f('ix_set_fingerprints_fingerprint_hash'), 'set_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_set_fingerprints_live_set_id'), 'set_fingerprints', ['live_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_fingerprints_live_set_id'), table_name='set_fingerprints')
    op.drop_index(op.f('ix_set_fingerprints_fingerprint_hash'), table_name='set_fingerprints')
    op.drop_table('set_fingerprints')
    op.drop_table('live_set_tags')
    op.drop_table('live_set_artists')
    op.drop_index(op.f('ix_live_sets_venue_id'), table_name='live_sets')
    op.drop_index(op.f('ix_live_sets_uploaded_by'), table_name='live_sets')
    op.drop_index(op.f('ix_live_sets_slug'), table_name='live_sets')
    op.drop_index(op.f('ix_live_sets_party_id'), table_name='live_sets')
    op.drop_index(op.f('ix_live_sets_date'), table_name='live_sets')
    op.drop_table('live_sets')
    op.drop_index(op.f('ix_parties_venue_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_slug'), table_name='parties')
    op.drop_index(op.f('ix_parties_series_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_venues_slug'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_series_slug'), table_name='series')
    op.drop_table('series')
    op.drop_table('media_roots')
    op.drop_index(op.f('ix_artists_slug'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
